-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE communication_records (
  id TEXT PRIMARY KEY,
  contact_id TEXT NOT NULL,
  date TEXT NOT NULL,
  type TEXT NOT NULL,
  summary TEXT NOT NULL,
  details TEXT,
  follow_up_date TEXT,
  follow_up_note TEXT,
  follow_up_done BOOLEAN DEFAULT 0
);

CREATE TABLE connections (
  id TEXT PRIMARY KEY,
  source_contact_id TEXT NOT NULL,
  target_contact_id TEXT NOT NULL,
  type TEXT,
  FOREIGN KEY(source_contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
  FOREIGN KEY(target_contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);

CREATE TABLE contact_tags (
  contact_id TEXT NOT NULL,
  tag_id TEXT NOT NULL,
  PRIMARY KEY (contact_id, tag_id)
);

CREATE TABLE contacts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  avatar TEXT,
  title TEXT,
  company TEXT,
  bonjour_link TEXT,
  notes TEXT,
  created_at TEXT NOT NULL,
  last_contacted_at TEXT NOT NULL,
  interaction_count INTEGER DEFAULT 0,
  share_visible BOOLEAN DEFAULT 0,
  sensitive_notes TEXT
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE relationships (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  source_contact_id TEXT NOT NULL,
  target_contact_id TEXT NOT NULL,
  type TEXT,
  strength INTEGER DEFAULT 1,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE tags (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  label TEXT NOT NULL,
  category TEXT NOT NULL,
  color TEXT NOT NULL
);

-- INDEXS

CREATE INDEX comm_records_contact_id_idx ON communication_records(contact_id);

CREATE INDEX connections_source_idx ON connections(source_contact_id);

CREATE INDEX contacts_user_id_idx ON contacts(user_id);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_relationships_source ON relationships(source_contact_id);

CREATE INDEX idx_relationships_target ON relationships(target_contact_id);

CREATE INDEX idx_relationships_user_id ON relationships(user_id);

CREATE INDEX tags_user_id_idx ON tags(user_id);
