// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { contacts, connections } from "./db_schema";

export const connectionsRelations = relations(connections, ({one}) => ({
	contact_targetContactId: one(contacts, {
		fields: [connections.targetContactId],
		references: [contacts.id],
		relationName: "connections_targetContactId_contacts_id"
	}),
	contact_sourceContactId: one(contacts, {
		fields: [connections.sourceContactId],
		references: [contacts.id],
		relationName: "connections_sourceContactId_contacts_id"
	}),
}));

export const contactsRelations = relations(contacts, ({many}) => ({
	connections_targetContactId: many(connections, {
		relationName: "connections_targetContactId_contacts_id"
	}),
	connections_sourceContactId: many(connections, {
		relationName: "connections_sourceContactId_contacts_id"
	}),
}));